Repository Varenthein/WDP-1906-01, pull requests merged in 2019-07, with the labels that each got.

#6 WDP190601-38
  package.json
  src/partials/50_section-products.html
  src/sass/components/_button.scss
  src/scripts/app.js
  src/scripts/buttonState.js
Labels: conflicted files

#2 WDP190601-36
  src/partials/30_section-features.html
  src/sass/components/_feature-box.scss
Labels: requested changes

#4 WDP190601-41
  src/partials/70_section-blog-posts.html
  src/sass/_variables.scss
  src/sass/components/_post-box.scss
Labels: requested changes

#10 WDP190601-45
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: conflicted files

#13 WDP190601-52
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
  src/scripts/activateStar.js
  src/scripts/app.js
Labels: question

#15 WDP190601-49
  package-lock.json
  src/partials/90_footer.html
  src/sass/components/_footer.scss
Labels: requested changes

#20 WDP190601-50
  src/partials/50_section-products.html
  src/sass/components/_panel-bar.scss
Labels: requested changes

#21 WDP190601-53
  src/images/blog/blog_004.jpg
  src/images/blog/blog_005.jpg
  src/images/blog/blog_006.jpg
  src/images/blog/blog_007.jpg
  src/images/blog/blog_008.jpg
  src/images/blog/blog_009.jpg
  src/partials/70_section-blog-posts.html
  src/sass/_custom.scss
  src/sass/components/_panel-bar.scss
  src/sass/components/_post-box.scss
  src/sass/style.scss
  src/scripts/app.js
  src/scripts/buttonState.js
Labels: question

#28 WDP190601-62
  src/images/brands/brand1.png
  src/images/brands/brand2.png
  src/images/brands/brand3.png
  src/images/brands/brand4.png
  src/images/brands/brand5.png
  src/images/brands/brand6.png
  src/index.html
  src/partials/20_section-promo.html
  src/partials/40_section-deals.html
  src/partials/80_section-brands.html
  src/sass/components/_brands-box.scss
  src/sass/components/_panel-bar.scss
  src/sass/components/_promo-box.scss
  src/sass/components/_section-deals.scss
  src/sass/style.scss
  src/scripts/app.js
Labels: conflicted files

#33 WDP190601-58
  src/partials/40_section-deals.html
  src/sass/components/_section-deals.scss
Labels: needs review

#35 WDP190601-62v2
  src/images/brands/brand1.png
  src/images/brands/brand2.png
  src/images/brands/brand3.png
  src/images/brands/brand4.png
  src/images/brands/brand5.png
  src/images/brands/brand6.png
  src/index.html
  src/partials/80_section-brands.html
  src/sass/components/_brands-box.scss
  src/sass/style.scss
Labels: needs review

#30 WDP190601-51
  src/index.html
  src/partials/50_section-products.html
  src/sass/components/_panel-bar.scss
  src/sass/components/_product-box.scss
  src/scripts/app.js
  src/scripts/newFurnitureSlider.js
Labels: question, requested changes
